
/* Drop Tables */

DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS BOOKSHELF;




/* Create Tables */

CREATE TABLE BOOK
(
	ID NUMERIC(8) NOT NULL,
	NAME VARCHAR(512) NOT NULL,
	VOLUME NUMERIC(8),
	DESCRIPTION VARCHAR(1028),
	PICTURE VARCHAR(1024),
	CREATED_AT TIMESTAMP(6) NOT NULL,
	CREATED_USER_ID VARCHAR(32) NOT NULL,
	UPDATED_AT TIMESTAMP(6),
	UPDATED_USER_ID VARCHAR(32),
	BOOKSHELF_ID NUMERIC(8) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE BOOKSHELF
(
	ID NUMERIC(8) NOT NULL,
	NAME VARCHAR(512) NOT NULL UNIQUE,
	CREATED_AT TIMESTAMP(6) NOT NULL,
	CREATED_USER_ID VARCHAR(32) NOT NULL,
	UPDATED_AT TIMESTAMP(6),
	UPDATED_USER_ID VARCHAR(32),
	PRIMARY KEY (ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE BOOK
	ADD FOREIGN KEY (BOOKSHELF_ID)
	REFERENCES BOOKSHELF (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON TABLE BOOK IS '本';
COMMENT ON COLUMN BOOK.ID IS 'ID';
COMMENT ON COLUMN BOOK.NAME IS '名称';
COMMENT ON COLUMN BOOK.VOLUME IS '巻数';
COMMENT ON COLUMN BOOK.DESCRIPTION IS '説明';
COMMENT ON COLUMN BOOK.PICTURE IS '本画像';
COMMENT ON COLUMN BOOK.CREATED_AT IS '作成日時';
COMMENT ON COLUMN BOOK.CREATED_USER_ID IS '作成者ユーザID';
COMMENT ON COLUMN BOOK.UPDATED_AT IS '更新日時';
COMMENT ON COLUMN BOOK.UPDATED_USER_ID IS '更新者ユーザID';
COMMENT ON COLUMN BOOK.BOOKSHELF_ID IS '本棚ID';
COMMENT ON TABLE BOOKSHELF IS '本棚';
COMMENT ON COLUMN BOOKSHELF.ID IS 'ID';
COMMENT ON COLUMN BOOKSHELF.NAME IS '名称';
COMMENT ON COLUMN BOOKSHELF.CREATED_AT IS '作成日時';
COMMENT ON COLUMN BOOKSHELF.CREATED_USER_ID IS '作成者ID';
COMMENT ON COLUMN BOOKSHELF.UPDATED_AT IS '更新日時';
COMMENT ON COLUMN BOOKSHELF.UPDATED_USER_ID IS '更新者ユーザID';



